### ISSUE TITLE
Create Dockerfile for deployment (user's localhost version)

### ISSUE THREAD

**Issue by leobcc** [ADS-2023-TH3/falcon_ml#27]

**Comment by alex-pv01** [comment]
Docker deployment file is already pushed and working, whoever the app files to read the dataset from the given path. we need to change how the app reads the dataset

**Comment by davidrosado4** [comment]
Thanks Alex. I update the issue. Yesterday we solve it. You modify the structure of the repo to create the dockerfile. I change a little bug with the spotlight recommender so that it is finally working.
